In [11]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt
import re

In [12]:
df_category = pd.read_csv('category.csv')
df_customers = pd.read_csv('customers.csv')
df_geolocation = pd.read_csv('geolocation.csv')
df_order_items = pd.read_csv('order_items.csv')
df_order_payments = pd.read_csv('order_payments.csv')
df_order_reviews = pd.read_csv('order_reviews.csv')
df_products = pd.read_csv('products.csv')
df_sellers = pd.read_csv('sellers.csv')
df_teste = pd.read_csv('teste_kaggle.csv')

In [13]:
#base de customers
df = df_teste.merge(df_customers)

#base de geolocation
df_geolocation = df_geolocation.rename(columns={'geolocation_zip_code_prefix': 'customer_zip_code_prefix'})
df_geolocation = df_geolocation.drop_duplicates(subset=['customer_zip_code_prefix'])
df = df.merge(df_geolocation, on='customer_zip_code_prefix', how='left')

#base de order_payments
df_order_payments = df_order_payments.drop_duplicates(subset=['order_id'])
df = df.merge(df_order_payments, on='order_id', how='left')

#base de sellers
df_sellers = df_sellers.drop_duplicates(subset=['seller_id'])
df2 = df_order_items.merge(df_sellers, on='seller_id', how='left')

#base de products
df_products = df_products.drop_duplicates(subset=['product_id'])
df2 = df2.merge(df_products, on='product_id', how='left')

#base de category
df_category = df_category.drop_duplicates(subset=['product_category_name'])
df2 = df2.merge(df_category, on='product_category_name', how='left')

#merge final
df_final = df2.merge(df, on='order_id', how='left')
df_final.to_csv('Base_Teste_Consolidada.csv', index=False)

df_final

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,...,customer_city,customer_state,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,payment_sequential,payment_type,payment_installments,payment_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,27277,volta redonda,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,3471,sao paulo,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,37564,borda da mata,MG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,14403,franca,SP,...,atibaia,sao paulo,-23.144923,-46.539830,atibaia,SP,1.0,credit_card,2.0,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,87900,loanda,PR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,88303,itajai,SC,...,sao luis,MA,-2.490420,-44.303287,sao luis,MA,1.0,boleto,1.0,343.40
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,1206,sao paulo,SP,...,curitiba,PR,-25.601485,-49.317700,curitiba,PR,1.0,boleto,1.0,386.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,80610,curitiba,PR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,4733,sao paulo,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,14940,ibitinga,SP,...,BOTUCATU,SP,-22.908684,-48.440255,botucatu,SP,1.0,credit_card,1.0,55.79

In [14]:
import pandas as pd

# Base inicial de teste
df = df_teste.copy()

# Merge com a base de customers
df_customers = df_customers.drop_duplicates(subset=['customer_id'])
df = df.merge(df_customers, on='customer_id', how='left')

# Merge com a base de geolocation
df_geolocation = df_geolocation.rename(columns={'geolocation_zip_code_prefix': 'customer_zip_code_prefix'})
df_geolocation = df_geolocation.drop_duplicates(subset=['customer_zip_code_prefix'])
df = df.merge(df_geolocation, on='customer_zip_code_prefix', how='left')

# Merge com a base de order_payments
df_order_payments = df_order_payments.drop_duplicates(subset=['order_id'])
df = df.merge(df_order_payments, on='order_id', how='left')

# Base intermediária 2 para sellers e products
df_sellers = df_sellers.drop_duplicates(subset=['seller_id'])
df2 = df_order_items.merge(df_sellers, on='seller_id', how='left')

# Merge com a base de products
df_products = df_products.drop_duplicates(subset=['product_id'])
df2 = df2.merge(df_products, on='product_id', how='left')

# Merge com a base de category
df_category = df_category.drop_duplicates(subset=['product_category_name'])
df2 = df2.merge(df_category, on='product_category_name', how='left')

# Merge final com a base de teste
df_final = df2.merge(df, on='order_id', how='left')

# Confirmar se a quantidade de linhas se manteve
print("Linhas antes do merge final:", len(df))
print("Linhas após o merge final:", len(df_final))

# Salvar o DataFrame consolidado
df_final.to_csv('Base_Teste_Consolidada.csv', index=False)

Linhas antes do merge final: 28152
Linhas após o merge final: 112650

In [15]:
#retirando as colunas menos importantes
df = df_final.drop(columns=['product_id','seller_id','product_name_lenght','product_description_lenght',
                            'product_photos_qty','product_category_name_english','customer_id','customer_unique_id',
                            'payment_sequential','payment_type','payment_installments'])

#criando a coluna de volume
df['product_volume'] = df['product_length_cm']*df['product_height_cm']*df['product_width_cm']
df = df.drop(columns=['product_length_cm', 'product_height_cm', 'product_width_cm'])

#adicionando as localizações dos sellers
df_geolocation = df_geolocation.rename(columns={'customer_zip_code_prefix': 'seller_zip_code_prefix'})
df_geolocation = df_geolocation.drop_duplicates(subset=['seller_zip_code_prefix'])
df = df.merge(df_geolocation, on='seller_zip_code_prefix', how='left')
df = df.rename(columns={'geolocation_lat_x': 'geolocation_lat_customer', 'geolocation_lng_x': 'geolocation_lng_customer', 
                        'geolocation_city_x': 'geolocation_city_customer', 'geolocation_state_x': 'geolocation_state_customer', 
                        'geolocation_lat_y': 'geolocation_lat_seller', 'geolocation_lng_y': 'geolocation_lng_seller', 
                        'geolocation_city_y': 'geolocation_city_seller', 'geolocation_state_y': 'geolocation_state_seller'})

#função para calcular a distância usando a fórmula de Haversine
def calcular_distancia(lat1, lon1, lat2, lon2):
    # Converter as coordenadas de graus para radianos
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    # Diferenças das coordenadas
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    # Fórmula de Haversine
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    # Raio da Terra em quilômetros
    raio_terra_km = 6371
    distancia = raio_terra_km * c
    return distancia

df['distancia_km'] = df.apply(lambda row: calcular_distancia(row['geolocation_lat_customer'], row['geolocation_lng_customer'], 
                                                             row['geolocation_lat_seller'], row['geolocation_lng_seller']), axis=1)

# Convertendo as colunas para o formato datetime
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])

# Criando as colunas com a diferença de tempo em dias
df['purchase_to_approval_days'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.days

# Dicionário de mapeamento das subcategorias para as novas categorias principais
mapeamento_categorias = {
    # Moda e Acessórios
    'fashion_bolsas_e_acessorios': 'Moda e Acessórios',
    'fashion_calcados': 'Moda e Acessórios',
    'fashion_roupa_masculina': 'Moda e Acessórios',
    'fashion_roupa_feminina': 'Moda e Acessórios',
    'fashion_underwear_e_moda_praia': 'Moda e Acessórios',
    'fashion_esporte': 'Moda e Acessórios',
    'fashion_roupa_infanto_juvenil': 'Moda e Acessórios',
    
    # Beleza e Saúde
    'beleza_saude': 'Beleza e Saúde',
    'perfumaria': 'Beleza e Saúde',
    'fraldas_higiene': 'Beleza e Saúde',

    # Tecnologia e Eletrônicos
    'informatica_acessorios': 'Tecnologia e Eletrônicos',
    'tablets_impressao_imagem': 'Tecnologia e Eletrônicos',
    'eletronicos': 'Tecnologia e Eletrônicos',
    'telefonia': 'Tecnologia e Eletrônicos',
    'telefonia_fixa': 'Tecnologia e Eletrônicos',
    'audio': 'Tecnologia e Eletrônicos',
    'cine_foto': 'Tecnologia e Eletrônicos',
    'pcs': 'Tecnologia e Eletrônicos',
    'consoles_games': 'Tecnologia e Eletrônicos',

    # Casa e Decoração
    'moveis_decoracao': 'Casa e Decoração',
    'cama_mesa_banho': 'Casa e Decoração',
    'moveis_cozinha_area_de_servico_jantar_e_jardim': 'Casa e Decoração',
    'moveis_sala': 'Casa e Decoração',
    'moveis_escritorio': 'Casa e Decoração',
    'moveis_colchao_e_estofado': 'Casa e Decoração',
    'moveis_quarto': 'Casa e Decoração',
    'casa_conforto': 'Casa e Decoração',
    'casa_conforto_2': 'Casa e Decoração',

    # Utilidades Domésticas e Eletrodomésticos
    'eletroportateis': 'Utilidades Domésticas e Eletrodomésticos',
    'portateis_casa_forno_e_cafe': 'Utilidades Domésticas e Eletrodomésticos',
    'eletrodomesticos': 'Utilidades Domésticas e Eletrodomésticos',
    'eletrodomesticos_2': 'Utilidades Domésticas e Eletrodomésticos',
    'climatizacao': 'Utilidades Domésticas e Eletrodomésticos',

    # Alimentos e Bebidas
    'alimentos': 'Alimentos e Bebidas',
    'bebidas': 'Alimentos e Bebidas',
    'alimentos_bebidas': 'Alimentos e Bebidas',

    # Esportes e Lazer
    'esporte_lazer': 'Esportes e Lazer',
    'cool_stuff': 'Esportes e Lazer',
    'malas_acessorios': 'Esportes e Lazer',
    'artigos_de_festas': 'Esportes e Lazer',
    'artigos_de_natal': 'Esportes e Lazer',

    # Livros, Música e Entretenimento
    'livros_tecnicos': 'Livros, Música e Entretenimento',
    'livros_interesse_geral': 'Livros, Música e Entretenimento',
    'livros_importados': 'Livros, Música e Entretenimento',
    'musica': 'Livros, Música e Entretenimento',
    'cds_dvds_musicais': 'Livros, Música e Entretenimento',
    'dvds_blu_ray': 'Livros, Música e Entretenimento',

    # Ferramentas e Construção
    'construcao_ferramentas_construcao': 'Ferramentas e Construção',
    'construcao_ferramentas_jardim': 'Ferramentas e Construção',
    'ferramentas_jardim': 'Ferramentas e Construção',
    'construcao_ferramentas_ferramentas': 'Ferramentas e Construção',
    'construcao_ferramentas_iluminacao': 'Ferramentas e Construção',
    'construcao_ferramentas_seguranca': 'Ferramentas e Construção',

    # Outros e Indústria
    'industria_comercio_e_negocios': 'Outros e Indústria',
    'pet_shop': 'Outros e Indústria',
    'seguros_e_servicos': 'Outros e Indústria',
    'agro_industria_e_comercio': 'Outros e Indústria',
    'sinalizacao_e_seguranca': 'Outros e Indústria',
    'artes': 'Outros e Indústria',
    'artes_e_artesanato': 'Outros e Indústria',
    'la_cuisine': 'Outros e Indústria',
    'market_place': 'Outros e Indústria',
}

df = df.drop(columns=['order_approved_at', 'order_purchase_timestamp', 'shipping_limit_date', 'customer_zip_code_prefix', 
                      'seller_zip_code_prefix',	'geolocation_lat_customer', 'geolocation_lng_customer', 
                      'geolocation_lat_seller', 'geolocation_lng_seller'])

# Adicionar nova coluna 'categoria_principal' com base na coluna 'subcategoria'
df['categoria_principal'] = df['product_category_name'].map(mapeamento_categorias)

# Opcional: remover a coluna de subcategorias antiga
df = df.drop(columns=['product_category_name'])

# Função para normalizar os nomes das cidades
def normalizar_nome_cidade(nome):
    nome = nome.lower()                           # Converte para minúsculas
    nome = re.sub(r'[^a-z\s]', '', nome)          # Remove pontuações e caracteres especiais
    nome = re.sub(r'\s+', ' ', nome).strip()      # Remove espaços extras
    return nome

# Dicionário de substituições para padronizar variações de nomes comuns
substituicoes = {
    "sp": "sao paulo",
    "so paulo": "sao paulo",
    "saopaulo": "sao paulo",
    "SAO PAULO": "sao paulo",
    "RIO DE JANEIRO": "rio de janeiro",
}

# Função para aplicar as substituições específicas
def padronizar_cidade(nome):
    return substituicoes.get(nome, nome)  # Substitui se a cidade estiver no dicionário, caso contrário, mantém o original
df['seller_city'] = df['seller_city'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)
df['customer_city'] = df['customer_city'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)

#função para arrumar os estados
mapa_estados_siglas = {
    'acre': 'AC', 'alagoas': 'AL', 'amapa': 'AP', 'amazonas': 'AM',
    'bahia': 'BA', 'ceara': 'CE', 'distritofederal': 'DF', 'espiritosanto': 'ES',
    'goias': 'GO', 'maranhao': 'MA', 'matogrosso': 'MT', 'matogrossodosul': 'MS',
    'minasgerais': 'MG', 'minas': 'MG','para': 'PA', 'paraiba': 'PB', 'parana': 'PR',
    'pernambuco': 'PE', 'piaui': 'PI', 'riodejaneiro': 'RJ', 'rio': 'RJ', 'riograndedonorte': 'RN',
    'riograndedosul': 'RS', 'rondonia': 'RO', 'roraima': 'RR', 'santacatarina': 'SC',
    'saopaulo': 'SP', 'sergipe': 'SE', 'tocantins': 'TO'
}
siglas_validas = set(mapa_estados_siglas.values())
def sigla(estado):            
    if isinstance(estado , str) and estado.upper() in siglas_validas:  
        return estado.upper()
    else:    
        sigla = mapa_estados_siglas.get(estado, np.nan)
        return sigla
df['seller_state'] = df['seller_state'].fillna('').apply(sigla)
df['customer_state'] = df['customer_state'].fillna('').apply(sigla)

# Preenchendo valores NaN com string vazia antes de aplicar a normalização e padronização nas colunas de cidades
df['geolocation_city_customer'] = df['geolocation_city_customer'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)
df['geolocation_city_seller'] = df['geolocation_city_seller'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)

df.to_csv('Base_Teste_Consolidada.csv', index=False)
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 18 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   order_id                    112650 non-null  object
 1   order_item_id               112650 non-null  int64
 2   price                       112473 non-null  float64
 3   freight_value               111574 non-null  float64
 4   seller_city                 112650 non-null  object
 5   seller_state                112650 non-null  object
 6   product_weight_g            112632 non-null  float64
 7   customer_city               112650 non-null  object
 8   customer_state              14282 non-null   object
 9   geolocation_city_customer   112650 non-null  object
 10  geolocation_state_customer  31986 non-null   object
 11  payment_value               32081 non-null   float64
 12  product_volume              112632 non-null  float64
 13  geolocation_city_seller     112650 non-null  object
 14  geolocation_state_seller    112397 non-null  object
 15  distancia_km                31937 non-null   float64
 16  purchase_to_approval_days   32081 non-null   float64
 17  categoria_principal         82817 non-null   object
dtypes: float64(7), int64(1), object(10)
memory usage: 15.5+ MB

,order_id,order_item_id,price,freight_value,seller_city,seller_state,product_weight_g,customer_city,customer_state,geolocation_city_customer,geolocation_state_customer,payment_value,product_volume,geolocation_city_seller,geolocation_state_seller,distancia_km,purchase_to_approval_days,categoria_principal
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,volta redonda,SP,650.0,,NaN,,NaN,NaN,3528.0,volta redonda,RJ,NaN,NaN,Esportes e Lazer
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,sao paulo,SP,30000.0,,NaN,,NaN,NaN,60000.0,sao paulo,SP,NaN,NaN,Outros e Indústria
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,borda da mata,MG,3050.0,,NaN,,NaN,NaN,14157.0,borda da mata,MG,NaN,NaN,Casa e Decoração
3,00024acbcdf0a6daa1e931b038114c75,1,12.99,12.79,franca,SP,200.0,atibaia,NaN,atibaia,SP,25.78,2400.0,franca,SP,301.951753,0.0,Beleza e Saúde
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,loanda,PR,3750.0,,NaN,,NaN,NaN,42000.0,loanda,PR,NaN,NaN,Ferramentas e Construção
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,299.99,43.41,itajai,SC,10150.0,sao luis,MA,sao luis,MA,343.40,53400.0,itajai,SC,2755.314485,1.0,NaN
112646,fffcd46ef2263f404302a634eb57f7eb,1,350.00,36.53,sao paulo,SP,8950.0,curitiba,PR,curitiba,PR,386.53,44460.0,sao paulo,SP,354.848852,2.0,Tecnologia e Eletrônicos
112647,fffce4705a9662cd70adb13d4a31832d,1,99.90,16.95,curitiba,PR,967.0,,NaN,,NaN,NaN,9576.0,curitiba,PR,NaN,NaN,Esportes e Lazer
112648,fffe18544ffabc95dfada21779c9644f,1,55.99,8.72,sao paulo,SP,100.0,,NaN,,NaN,NaN,8000.0,sao paulo,SP,NaN,NaN,Tecnologia e Eletrônicos
112649,fffe41c64501cc87c801fd61db3f6244,1,43.00,12.79,ibitinga,SP,600.0,botucatu,SP,botucatu,SP,55.79,1710.0,ibitinga,SP,133.230980,0.0,Casa e Decoração