In [9]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib as plt
import re

In [10]:
df_category = pd.read_csv('category.csv')
df_customers = pd.read_csv('customers.csv')
df_geolocation = pd.read_csv('geolocation.csv')
df_order_items = pd.read_csv('order_items.csv')
df_order_payments = pd.read_csv('order_payments.csv')
df_order_reviews = pd.read_csv('order_reviews.csv')
df_products = pd.read_csv('products.csv')
df_sellers = pd.read_csv('sellers.csv')
df_treino = pd.read_csv('treino.csv')

In [11]:
#base de customers
df = df_treino.merge(df_customers)

#bse de geolocation
df_geolocation = df_geolocation.rename(columns={'geolocation_zip_code_prefix': 'customer_zip_code_prefix'})
df_geolocation = df_geolocation.drop_duplicates(subset=['customer_zip_code_prefix'])
df = df.merge(df_geolocation, on='customer_zip_code_prefix', how='left')

#base de order_payments
df_order_payments = df_order_payments.drop_duplicates(subset=['order_id'])
df = df.merge(df_order_payments, on='order_id', how='left')

#base de order_reviews
df_order_reviews = df_order_reviews.drop_duplicates(subset=['order_id'])
df = df.merge(df_order_reviews, on='order_id', how='left')

#base de sellers
df_sellers = df_sellers.drop_duplicates(subset=['seller_id'])
df2 = df_order_items.merge(df_sellers, on='seller_id', how='left')

#base de products
df_products = df_products.drop_duplicates(subset=['product_id'])
df2 = df2.merge(df_products, on='product_id', how='left')

#base de category
df_category = df_category.drop_duplicates(subset=['product_category_name'])
df2 = df2.merge(df_category, on='product_category_name', how='left')

#merge final
df_final = df2.merge(df, on='order_id', how='left')
df_final.to_csv('Base_Treino_Consolidada.csv', index=False)

df_final

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,seller_zip_code_prefix,seller_city,seller_state,...,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,27277,volta redonda,SP,...,1.0,credit_card,2.0,72.19,97ca439bc427b48bc1cd7177abe71365,5.0,NaN,"Perfeito, produto entregue antes do combinado.",2017-09-21 00:00:00,2017-09-22 10:57:03
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,3471,sao paulo,SP,...,1.0,credit_card,3.0,259.83,7b07bacd811c4117b742569b04ce3580,4.0,NaN,NaN,2017-05-13 00:00:00,2017-05-15 11:34:13
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,37564,borda da mata,MG,...,1.0,credit_card,5.0,216.87,0c5b33dea94867d1ac402749e5438e8b,5.0,NaN,Chegou antes do prazo previsto e o produto sur...,2018-01-23 00:00:00,2018-01-23 16:06:31
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,14403,franca,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,87900,loanda,PR,...,1.0,credit_card,3.0,218.04,940144190dcba6351888cafa43f3a3a5,5.0,NaN,Gostei pois veio no prazo determinado .,2017-03-02 00:00:00,2017-03-03 10:54:59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,88303,itajai,SC,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,1206,sao paulo,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,80610,curitiba,PR,...,1.0,credit_card,3.0,116.85,dbdd81cd59a1a9f94a10a990b4d48dce,5.0,NaN,NaN,2017-10-29 00:00:00,2017-10-29 21:33:52
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,4733,sao paulo,SP,...,1.0,credit_card,3.0,64.71,fba117c9ac40d41ca7be54741f471303,5.0,NaN,Recebi o produto antes do prazo e corretamente.,2017-08-17 00:00:00,2017-08-18 12:24:05
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,14940,ibitinga,SP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#retirando as colunas menos importantes
df = df_final.drop(columns=[ 'product_id','seller_id','product_name_lenght','product_description_lenght',
                            'product_photos_qty','product_category_name_english','customer_id','customer_unique_id',
                            'payment_sequential','payment_type','payment_installments','review_id','review_score','review_comment_title',
                            'review_comment_message','review_creation_date','review_answer_timestamp'])

# Renomear a coluna "delivery_time (days)" para "delivery_time"
df = df.rename(columns={'delivery_time (days)': 'delivery_time'})

#criando a coluna de volume
df['product_volume'] = df['product_length_cm']*df['product_height_cm']*df['product_width_cm']
df = df.drop(columns=['product_length_cm', 'product_height_cm', 'product_width_cm'])

#adicionando as localizações dos sellers
df_geolocation = df_geolocation.rename(columns={'customer_zip_code_prefix': 'seller_zip_code_prefix'})
df_geolocation = df_geolocation.drop_duplicates(subset=['seller_zip_code_prefix'])
df = df.merge(df_geolocation, on='seller_zip_code_prefix', how='left')
df = df.rename(columns={'geolocation_lat_x': 'geolocation_lat_customer', 'geolocation_lng_x': 'geolocation_lng_customer', 
                        'geolocation_city_x': 'geolocation_city_customer', 'geolocation_state_x': 'geolocation_state_customer', 
                        'geolocation_lat_y': 'geolocation_lat_seller', 'geolocation_lng_y': 'geolocation_lng_seller', 
                        'geolocation_city_y': 'geolocation_city_seller', 'geolocation_state_y': 'geolocation_state_seller'})

#função para calcular a distância usando a fórmula de Haversine
def calcular_distancia(lat1, lon1, lat2, lon2):
    # Converter as coordenadas de graus para radianos
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    # Diferenças das coordenadas
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    # Fórmula de Haversine
    a = np.sin(dlat / 2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    # Raio da Terra em quilômetros
    raio_terra_km = 6371
    distancia = raio_terra_km * c
    return distancia

df['distancia_km'] = df.apply(lambda row: calcular_distancia(row['geolocation_lat_customer'], row['geolocation_lng_customer'], 
                                                             row['geolocation_lat_seller'], row['geolocation_lng_seller']), axis=1)

df = df.drop(columns=['customer_zip_code_prefix', 'seller_zip_code_prefix',	'geolocation_lat_customer', 'geolocation_lng_customer', 
                      'geolocation_lat_seller', 'geolocation_lng_seller'])

# Convertendo as colunas para o formato datetime
df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])
df['order_approved_at'] = pd.to_datetime(df['order_approved_at'])
df['order_delivered_carrier_date'] = pd.to_datetime(df['order_delivered_carrier_date'])
df['order_delivered_customer_date'] = pd.to_datetime(df['order_delivered_customer_date'])

# Criando as colunas com a diferença de tempo 
df['purchase_to_approval_days'] = (df['order_approved_at'] - df['order_purchase_timestamp']).dt.days
df['approval_to_carrier_days'] = (df['order_delivered_carrier_date'] - df['order_approved_at']).dt.days
df['carrier_to_customer_days'] = (df['order_delivered_customer_date'] - df['order_delivered_carrier_date']).dt.days

# Dicionário de mapeamento das subcategorias para as novas categorias principais
mapeamento_categorias = {
    # Moda e Acessórios
    'fashion_bolsas_e_acessorios': 'Moda e Acessórios',
    'fashion_calcados': 'Moda e Acessórios',
    'fashion_roupa_masculina': 'Moda e Acessórios',
    'fashion_roupa_feminina': 'Moda e Acessórios',
    'fashion_underwear_e_moda_praia': 'Moda e Acessórios',
    'fashion_esporte': 'Moda e Acessórios',
    'fashion_roupa_infanto_juvenil': 'Moda e Acessórios',
    
    # Beleza e Saúde
    'beleza_saude': 'Beleza e Saúde',
    'perfumaria': 'Beleza e Saúde',
    'fraldas_higiene': 'Beleza e Saúde',

    # Tecnologia e Eletrônicos
    'informatica_acessorios': 'Tecnologia e Eletrônicos',
    'tablets_impressao_imagem': 'Tecnologia e Eletrônicos',
    'eletronicos': 'Tecnologia e Eletrônicos',
    'telefonia': 'Tecnologia e Eletrônicos',
    'telefonia_fixa': 'Tecnologia e Eletrônicos',
    'audio': 'Tecnologia e Eletrônicos',
    'cine_foto': 'Tecnologia e Eletrônicos',
    'pcs': 'Tecnologia e Eletrônicos',
    'consoles_games': 'Tecnologia e Eletrônicos',

    # Casa e Decoração
    'moveis_decoracao': 'Casa e Decoração',
    'cama_mesa_banho': 'Casa e Decoração',
    'moveis_cozinha_area_de_servico_jantar_e_jardim': 'Casa e Decoração',
    'moveis_sala': 'Casa e Decoração',
    'moveis_escritorio': 'Casa e Decoração',
    'moveis_colchao_e_estofado': 'Casa e Decoração',
    'moveis_quarto': 'Casa e Decoração',
    'casa_conforto': 'Casa e Decoração',
    'casa_conforto_2': 'Casa e Decoração',

    # Utilidades Domésticas e Eletrodomésticos
    'eletroportateis': 'Utilidades Domésticas e Eletrodomésticos',
    'portateis_casa_forno_e_cafe': 'Utilidades Domésticas e Eletrodomésticos',
    'eletrodomesticos': 'Utilidades Domésticas e Eletrodomésticos',
    'eletrodomesticos_2': 'Utilidades Domésticas e Eletrodomésticos',
    'climatizacao': 'Utilidades Domésticas e Eletrodomésticos',

    # Alimentos e Bebidas
    'alimentos': 'Alimentos e Bebidas',
    'bebidas': 'Alimentos e Bebidas',
    'alimentos_bebidas': 'Alimentos e Bebidas',

    # Esportes e Lazer
    'esporte_lazer': 'Esportes e Lazer',
    'cool_stuff': 'Esportes e Lazer',
    'malas_acessorios': 'Esportes e Lazer',
    'artigos_de_festas': 'Esportes e Lazer',
    'artigos_de_natal': 'Esportes e Lazer',

    # Livros, Música e Entretenimento
    'livros_tecnicos': 'Livros, Música e Entretenimento',
    'livros_interesse_geral': 'Livros, Música e Entretenimento',
    'livros_importados': 'Livros, Música e Entretenimento',
    'musica': 'Livros, Música e Entretenimento',
    'cds_dvds_musicais': 'Livros, Música e Entretenimento',
    'dvds_blu_ray': 'Livros, Música e Entretenimento',

    # Ferramentas e Construção
    'construcao_ferramentas_construcao': 'Ferramentas e Construção',
    'construcao_ferramentas_jardim': 'Ferramentas e Construção',
    'ferramentas_jardim': 'Ferramentas e Construção',
    'construcao_ferramentas_ferramentas': 'Ferramentas e Construção',
    'construcao_ferramentas_iluminacao': 'Ferramentas e Construção',
    'construcao_ferramentas_seguranca': 'Ferramentas e Construção',

    # Outros e Indústria
    'industria_comercio_e_negocios': 'Outros e Indústria',
    'pet_shop': 'Outros e Indústria',
    'seguros_e_servicos': 'Outros e Indústria',
    'agro_industria_e_comercio': 'Outros e Indústria',
    'sinalizacao_e_seguranca': 'Outros e Indústria',
    'artes': 'Outros e Indústria',
    'artes_e_artesanato': 'Outros e Indústria',
    'la_cuisine': 'Outros e Indústria',
    'market_place': 'Outros e Indústria',
}

# Adicionar nova coluna 'categoria_principal' com base na coluna 'subcategoria'
df['categoria_principal'] = df['product_category_name'].map(mapeamento_categorias)

# Opcional: remover a coluna de subcategorias antiga
df = df.drop(columns=['product_category_name'])

# Removendo linhas com valores nulos na coluna 'delivery_time'
df = df.dropna(subset=['delivery_time'])

# Função para normalizar os nomes das cidades
def normalizar_nome_cidade(nome):
    nome = nome.lower()                           # Converte para minúsculas
    nome = re.sub(r'[^a-z\s]', '', nome)          # Remove pontuações e caracteres especiais
    nome = re.sub(r'\s+', ' ', nome).strip()      # Remove espaços extras
    return nome

# Dicionário de substituições para padronizar variações de nomes comuns
substituicoes = {
    "sp": "sao paulo",
    "so paulo": "sao paulo",
    "saopaulo": "sao paulo",
    "SAO PAULO": "sao paulo",
    "RIO DE JANEIRO": "rio de janeiro",
}

# Função para aplicar as substituições específicas
def padronizar_cidade(nome):
    return substituicoes.get(nome, nome)  # Substitui se a cidade estiver no dicionário, caso contrário, mantém o original
df['seller_city'] = df['seller_city'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)
df['customer_city'] = df['customer_city'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)

#função para arrumar os estados
mapa_estados_siglas = {
    'acre': 'AC', 'alagoas': 'AL', 'amapa': 'AP', 'amazonas': 'AM',
    'bahia': 'BA', 'ceara': 'CE', 'distritofederal': 'DF', 'espiritosanto': 'ES',
    'goias': 'GO', 'maranhao': 'MA', 'matogrosso': 'MT', 'matogrossodosul': 'MS',
    'minasgerais': 'MG', 'minas': 'MG','para': 'PA', 'paraiba': 'PB', 'parana': 'PR',
    'pernambuco': 'PE', 'piaui': 'PI', 'riodejaneiro': 'RJ', 'rio': 'RJ', 'riograndedonorte': 'RN',
    'riograndedosul': 'RS', 'rondonia': 'RO', 'roraima': 'RR', 'santacatarina': 'SC',
    'saopaulo': 'SP', 'sergipe': 'SE', 'tocantins': 'TO'
}
siglas_validas = set(mapa_estados_siglas.values())
def sigla(estado):            
    if isinstance(estado , str) and estado.upper() in siglas_validas:  
        return estado.upper()
    else:    
        sigla = mapa_estados_siglas.get(estado, np.nan)
        return sigla
df['seller_state'] = df['seller_state'].fillna('').apply(sigla)
df['customer_state'] = df['customer_state'].fillna('').apply(sigla)

# Preenchendo valores NaN com string vazia antes de aplicar a normalização e padronização nas colunas de cidades
df['geolocation_city_customer'] = df['geolocation_city_customer'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)
df['geolocation_city_seller'] = df['geolocation_city_seller'].fillna('').apply(normalizar_nome_cidade).apply(padronizar_cidade)

#remoção de colunas extras
df = df.drop(columns=['shipping_limit_date','order_status', 'order_purchase_timestamp', 'order_delivered_carrier_date', 'seller_city', 'seller_state',
                      'delivery_time_model (days)', 'order_approved_at', 'order_delivered_customer_date', 'customer_state', 'customer_city'])


df.to_csv('Base_Treino_Consolidada.csv', index=False)
df.info()
df

<class 'pandas.core.frame.DataFrame'>
Index: 78115 entries, 0 to 112648
Data columns (total 17 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   order_id                    78115 non-null  object
 1   order_item_id               78115 non-null  int64
 2   price                       78007 non-null  float64
 3   freight_value               77378 non-null  float64
 4   product_weight_g            78097 non-null  float64
 5   delivery_time               78115 non-null  float64
 6   geolocation_city_customer   78115 non-null  object
 7   geolocation_state_customer  77922 non-null  object
 8   payment_value               78112 non-null  float64
 9   product_volume              78097 non-null  float64
 10  geolocation_city_seller     78115 non-null  object
 11  geolocation_state_seller    77915 non-null  object
 12  distancia_km                77723 non-null  float64
 13  purchase_to_approval_days   78100 non-null  float64
 14  approval_to_carrier_days    78099 non-null  float64
 15  carrier_to_customer_days    78114 non-null  float64
 16  categoria_principal         58491 non-null  object
dtypes: float64(10), int64(1), object(6)
memory usage: 10.7+ MB

,order_id,order_item_id,price,freight_value,product_weight_g,delivery_time,geolocation_city_customer,geolocation_state_customer,payment_value,product_volume,geolocation_city_seller,geolocation_state_seller,distancia_km,purchase_to_approval_days,approval_to_carrier_days,carrier_to_customer_days,categoria_principal
0,00010242fe8c5a6d1ba2dd792cb16214,1,58.90,13.29,650.0,7.61,campos dos goytacazes,RJ,72.19,3528.0,volta redonda,RJ,301.005664,0.0,6.0,1.0,Esportes e Lazer
1,00018f77f2f0320c557190d7a144bdd3,1,239.90,19.93,30000.0,16.22,santa fe do sul,SP,259.83,60000.0,sao paulo,SP,589.274140,0.0,8.0,8.0,Outros e Indústria
2,000229ec398224ef6ca0657da4fc703e,1,199.00,17.87,3050.0,7.95,par de minas,MG,216.87,14157.0,borda da mata,MG,312.495046,0.0,1.0,6.0,Casa e Decoração
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,199.90,18.14,3750.0,25.11,varzea paulista,SP,218.04,42000.0,loanda,PR,646.221788,0.0,11.0,13.0,Ferramentas e Construção
5,00048cc3ae777c65dbb7d2a0634bc1ea,1,21.90,12.69,450.0,6.67,uberaba,MG,34.59,2880.0,ribeirao preto,SP,161.597746,1.0,0.0,5.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112641,fffb9224b6fc7c43ebb0904318b10b5f,2,55.00,34.19,350.0,21.12,serra talhada,PE,356.76,2464.0,sao goncalo,RJ,1725.685456,0.0,13.0,7.0,NaN
112642,fffb9224b6fc7c43ebb0904318b10b5f,3,55.00,34.19,350.0,21.12,serra talhada,PE,356.76,2464.0,sao goncalo,RJ,1725.685456,0.0,13.0,7.0,NaN
112643,fffb9224b6fc7c43ebb0904318b10b5f,4,55.00,34.19,350.0,21.12,serra talhada,PE,356.76,2464.0,sao goncalo,RJ,1725.685456,0.0,13.0,7.0,NaN
112647,fffce4705a9662cd70adb13d4a31832d,1,99.90,16.95,967.0,4.80,sao paulo,SP,116.85,9576.0,curitiba,PR,338.827218,1.0,1.0,1.0,Esportes e Lazer
112648,fffe18544ffabc95dfada21779c9644f,1,55.99,8.72,100.0,1.96,vinhedo,SP,64.71,8000.0,sao paulo,SP,72.870476,0.0,0.0,1.0,Tecnologia e Eletrônicos