# Analisando o treino.csv

In [22]:
import pandas as pd

In [23]:
df_treino = pd.read_csv("treino.csv")
print(df_treino.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68324 entries, 0 to 68323
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       68324 non-null  object
 1   customer_id                    68324 non-null  object
 2   order_status                   68324 non-null  object
 3   order_purchase_timestamp       68324 non-null  object
 4   order_approved_at              68310 non-null  object
 5   order_delivered_carrier_date   68323 non-null  object
 6   order_delivered_customer_date  68324 non-null  object
 7   delivery_time (days)           68324 non-null  float64
 8   delivery_time_model (days)     68324 non-null  float64
dtypes: float64(2), object(7)
memory usage: 4.7+ MB
None

In [24]:
filtro = df_treino[df_treino['delivery_time_model (days)'] < 0]
print(filtro)

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, delivery_time (days), delivery_time_model (days)]
Index: []

In [25]:
filtro = df_treino[df_treino['delivery_time (days)'] < 0]
print(filtro)

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, delivery_time (days), delivery_time_model (days)]
Index: []

In [26]:
filtro = df_treino[df_treino['order_approved_at'].isnull()]
filtro

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,delivery_time (days),delivery_time_model (days)
3618,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaN,2017-02-23 12:04:47,2017-03-01 13:25:33,10.95,26.39
11410,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaN,2017-02-23 09:01:52,2017-03-02 10:05:06,11.89,30.47
13090,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38,10.78,26.44
15579,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaN,2017-02-22 11:23:10,2017-03-09 07:28:47,18.61,40.30
15925,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaN,2017-02-22 11:23:11,2017-03-02 11:09:19,12.92,30.45
18430,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,11.23,40.47
26323,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaN,2017-02-23 03:11:48,2017-03-02 03:41:58,11.09,35.94
27030,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaN,2017-02-23 07:23:36,2017-03-02 16:15:23,12.22,31.54
33242,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaN,2017-01-27 11:08:05,2017-02-06 14:22:19,17.66,55.06
42369,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03,13.79,30.28
43262,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaN,2017-02-23 03:09:14,2017-03-07 13:57:47,16.92,38.34
46426,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06,11.55,30.05
49691,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaN,2017-02-22 11:31:30,2017-03-03 11:47:47,13.83,33.34
58379,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaN,2017-02-22 11:23:11,2017-03-03 18:43:43,13.06,40.28

In [27]:
filtro = df_treino[df_treino['order_delivered_carrier_date'].isnull()]
filtro

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,delivery_time (days),delivery_time_model (days)
50234,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaN,2017-11-20 19:44:47,52.45,45.63

# Analisando category.csv

In [28]:
df_category = pd.read_csv('category.csv')
print(df_category.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None

A partir disso, temos que todas as categorias estão bem documentadas

# Analisando customers.csv

In [29]:
df_customers = pd.read_csv('customers.csv')
print(df_customers.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             64440 non-null  object
 4   customer_state            49441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

Daqui vemos que existem informações nulas dependendo da coluna

In [30]:
df_customers_clean = df_customers.drop_duplicates()
print(df_customers_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             64440 non-null  object
 4   customer_state            49441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

Não existem linhas duplicadas

In [31]:
filtro = df_customers_clean[df_customers_clean['customer_city'].isnull()]
filtro

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
10001,d7a30a15621f7476b06e0104ffef1cfa,4fdc62ec0c92703fde661756400e686d,30130,NaN,NaN
10002,f959348f343a0d3093d076e19e59d214,f3e06e60599257ec0a10ef53641c7806,22785,NaN,NaN
10003,ecff1b1c83d0c9237a8e5fa29684a78d,edd8b65865389a453e6d20c69b046ec5,85027,NaN,NaN
10004,511bc36a7fa92687dc6fd1c5bc5e120f,3c148fda438c986c7f659079038f308e,9941,NaN,NaN
10005,62291404156da337649d7e99334fbb6e,8533a540818c6fcd6c1eeaa4f1a40d45,29942,NaN,NaN
...,...,...,...,...,...
49996,b8e88388e911fd44511030aadba00add,18622f12981bb55e9a6f145fc0b4293d,37140,NaN,NaN
49997,ef75d5dbdc414838beb621629a99bad2,b1a6621008f2bb41784232794e2ef0a3,16920,NaN,NaN
49998,1a8eb043bc13de00b3d39495190dade0,a45cb33109cba712405ffa2093ec1545,22061,NaN,NaN
49999,744eaeaf58a86dbe348c4bf07a5b13e4,086746205f37aa6b1539135d3d7a265c,8576,NaN,NaN
50000,16ee708807a1311a42642843b427b00f,56238e115fd05d88a5e9ae565b8c2dbb,26292,NaN,rio

In [32]:
filtro = df_customers_clean[df_customers_clean['customer_state'].isnull()]
filtro

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
10000,139e44006d2388e32faf1718a043675e,406a1ba5fdcd424df15806a036414d61,41760,SALVADOR,NaN
10001,d7a30a15621f7476b06e0104ffef1cfa,4fdc62ec0c92703fde661756400e686d,30130,NaN,NaN
10002,f959348f343a0d3093d076e19e59d214,f3e06e60599257ec0a10ef53641c7806,22785,NaN,NaN
10003,ecff1b1c83d0c9237a8e5fa29684a78d,edd8b65865389a453e6d20c69b046ec5,85027,NaN,NaN
10004,511bc36a7fa92687dc6fd1c5bc5e120f,3c148fda438c986c7f659079038f308e,9941,NaN,NaN
...,...,...,...,...,...
89996,c9ca9573fa99e8e7f281d4ede1c2d2ea,369cf1ff7175710f0cea99e7e9f705a0,13801,mogi mirim,NaN
89997,21357ad9c60c967f999319f084ecdc83,c12900a741b4521f3d1aad16f0217184,38408,uberlandia,NaN
89998,d8e42482d0eda51e849d77e79d749534,43707df4380a4462039aafc51636104f,2353,sao paulo,NaN
89999,fa4560374dfb90c4e50a7da55cb5bf9c,9db0703d6dd2cc17ddfa3b1d509a9464,30150,belo horizonte,NaN
90000,44c231630b61cde2d9fd7c2311f0044c,5477633464629dfe2250f058ced9efa8,88048,florianopolis,NaN

In [33]:
# Preenchendo os NaNs em 'customer_state' com base nas informações de outras linhas que possuem o mesmo 'customer_city'
df_customers_clean['customer_state'] = df_customers_clean.groupby('customer_city')['customer_state'].transform(lambda x: x.ffill().bfill())

# Exibir o DataFrame após preenchimento
print(df_customers_clean.info())

df_customers_clean.to_csv('customers.csv', index=False)

C:\Users\ferna\AppData\Local\Temp\ipykernel_36008\2766810899.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_customers_clean['customer_state'] = df_customers_clean.groupby('customer_city')['customer_state'].transform(lambda x: x.ffill().bfill())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             64440 non-null  object
 4   customer_state            63951 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None

Tratamento rápido dos nan da coluna costume_state, pegando cidades já presentes que estão relacionadas a estados e preenchendo a partir disso

# Analisando geolocation.csv

In [34]:
df_geolocation = pd.read_csv('geolocation.csv')
print(df_geolocation.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None

Todas as localizações estão registradas

# Analisando order_items.csv

In [35]:
df_order_items = pd.read_csv('order_items.csv')
print(df_order_items.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                111573 non-null  float64
 6   freight_value        111574 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

In [36]:
df_order_items_clean = df_order_items.drop_duplicates()
print(df_order_items_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                111573 non-null  float64
 6   freight_value        111574 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

Não existem linhas duplicadas

In [37]:
filtro = df_order_items_clean[df_order_items_clean['price'].isnull()]
filtro

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
246,00a1e977cf6e672402963940db55d919,1,4834f24983a4f056e5ae64265f723aaf,5656537e588803a555b8eb41f07a944b,2018-07-27 16:35:16,NaN,7.75
247,00a250dbdb3153cc6ecf4d3f07ef6a17,1,ee0c1cf2fbeae95205b4aa506f1469f0,cc419e0650a3c5ba77189a1882b7556a,2017-12-15 18:15:33,NaN,7.78
295,00bc78808b22918a467b2fa4b8ef5d68,1,33fac76e7f17367dedaef7954bbb33b4,56642bcb79900e777d68e91915cb4267,2017-04-27 23:42:29,NaN,15.69
396,00f57f2ccce2a2e3f393fe8f5e616e0d,1,d6dc2dcbb3ef25e47ef82f3c013ab820,1025f0e2d44d7041d6cf58b6550e0bfa,2018-07-12 22:15:10,NaN,60.81
655,0184d4ddb259e1a4cfc2871888cf97b8,1,aa8627a375771ab01288705307ec4ae5,e333046ce6517bd8bb510291d44f0130,2017-09-07 22:31:42,NaN,16.16
...,...,...,...,...,...,...,...
112194,fee67a1d884fddbd3cd1da188db227e7,1,32c93bc61f5d2d836c65254f99a46b71,5f1dc28029d2c244352a68107ec2b542,2018-02-05 21:41:07,NaN,17.60
112238,fefde2c038077ee3f2cde28e6a6d94a7,1,a5341e3f8155dbb3e62323d3ea289729,ff063b022a9a0aab91bad2c9088760b7,2018-03-15 15:27:59,NaN,26.73
112250,ff0286485ce9c3f1d6ed22a4c7402060,3,41801d2ed5124923137ec39aeeea1e93,3be634553519fb6536a03e1358e9fdc7,2018-02-20 15:30:38,NaN,19.91
112303,ff229c2bb720b61c11d51e0249799aba,1,4413a608a42bd21bbf9d5abbd58c249a,7ddcbb64b5bc1ef36ca8c151f6ec77df,2017-11-03 21:10:07,NaN,43.44
112546,ffc0da1000e3fe80b745f005755bb814,1,d1606c4563d5481c8020de798866465e,06a2c3af7b3aee5d69171b0e14f0ee87,2018-07-11 00:30:50,NaN,30.04

In [38]:
filtro = df_order_items_clean[df_order_items_clean['freight_value'].isnull()]
filtro

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
128,004ba47bb589cdbc485e6025bd6d3c81,1,8c5876b1c7768217964f353bc7e64393,0db783cfcd3b73998abc6e10e59a102f,2017-12-29 20:48:10,49.00,NaN
268,00ace652c8a5072670f30674e5f19844,1,aba86c093ccdbac75b09111d57e50004,7c67e1448b00f6e969d365cea6b010ab,2018-02-02 09:07:49,116.60,NaN
404,00f86b368251d739f1896d41469b2b7a,1,9b08a09bf2fd9731cfca8cb3db24457c,392353362d22cc2c236e1ee81ff19890,2018-08-20 23:30:08,39.97,NaN
630,017499de14d22ef9e9a83ca54727480e,2,e0bb3159111d86828b5caef8725ff055,cd06602b43d8800bd0afad514919d35c,2017-07-17 16:15:24,101.00,NaN
692,019b8e16e30c8b9ad9bf87e039a27765,1,5d0386961a44323a9772e63672317131,5b67882648febfb6e1225e6ad7164f6b,2017-07-31 20:23:21,99.99,NaN
...,...,...,...,...,...,...,...
112149,fecd7c5fef57b69db425479e2cd41d3b,1,943c812216923e4244e83099e0c62a08,5b8154610ebb21fb90eb587365e673df,2017-10-18 03:30:48,141.00,NaN
112202,feea392f967ca802356423ab50673a92,1,130482add9fd75ccb6c57ba007694a2d,87142160b41353c4e5fca2360caf6f92,2017-12-21 14:31:42,105.00,NaN
112328,ff2e9b2298b4e147dd0e57c182d42528,1,542b3d80712d51eefe3a3cd1c5f4e8fe,537eb890efff034a88679788b647c564,2017-09-08 17:50:20,42.90,NaN
112363,ff40f38705c95a8eceea1a0db29bff66,1,461f43be3bdf8844e65b62d9ac2c7a5a,7d13fca15225358621be4086e1eb0964,2018-05-14 12:56:47,118.00,NaN
112367,ff4118746eaaed0d632211903070df50,2,372645c7439f9661fbbacfd129aa92ec,da8622b14eb17ae2831f4ac5b9dab84a,2017-07-13 18:23:15,99.90,NaN

In [39]:
# Preenchendo os NaNs em 'customer_state' com base nas informações de outras linhas que possuem o mesmo 'customer_city'
df_order_items_clean['price'] = df_order_items_clean.groupby('product_id')['price'].transform(lambda x: x.ffill().bfill())

# Exibir o DataFrame após preenchimento
print(df_order_items_clean.info())

df_order_items_clean.to_csv('order_items.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112473 non-null  float64
 6   freight_value        111574 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None

Limpeza de alguns nan a partir de outras linhas de order_id para checar o preço

# Analisando order_payments.csv

In [40]:
df_order_payments = pd.read_csv('order_payments.csv')
print(df_order_payments.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

In [41]:
df_order_payments_clean = df_order_payments.drop_duplicates()
print(df_order_payments_clean.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None

Todos order_payments estão bem registrados, além de não ter linhas duplicadas

# Analisando reviews.csv

In [42]:
df_order_reviews = pd.read_csv('order_reviews.csv')
print(df_order_reviews.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71171 entries, 0 to 71170
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                71171 non-null  object
 1   order_id                 71171 non-null  object
 2   review_score             64394 non-null  float64
 3   review_comment_title     1046 non-null   object
 4   review_comment_message   30021 non-null  object
 5   review_creation_date     71171 non-null  object
 6   review_answer_timestamp  71171 non-null  object
dtypes: float64(1), object(6)
memory usage: 3.8+ MB
None

# Analisando products.csv

In [43]:
df_products = pd.read_csv('products.csv')
print(df_products.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None

# Analisando sellers.csv

In [44]:
df_sellers = pd.read_csv('sellers.csv')
print(df_sellers.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None

A base sellers.csv está bem registrada